# Generated by Django 5.1 on 2024-08-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=64)),
                ('current_level', models.IntegerField()),
            ],
        ),
    ]
