# Generated by Django 4.2.15 on 2024-08-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_player_options_alter_player_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_id',
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
