# Generated by Django 4.2.15 on 2024-09-24 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniQuiz',
            fields=[
                ('quiz_id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=500)),
                ('time_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_quiz.miniquiz')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_id', models.IntegerField()),
                ('status', models.BooleanField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_quiz.miniquiz')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('time_answered', models.DateTimeField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_quiz.question')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer_text', models.CharField(max_length=200)),
                ('is_correct_answer', models.BooleanField()),
                ('mini_quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_quiz.miniquiz')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_quiz.question')),
            ],
        ),
    ]
