# Generated by Django 4.2.15 on 2024-08-19 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniQuiz',
            fields=[
                ('quiz_id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_quiz.miniquiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer_text', models.CharField(max_length=200)),
                ('is_correct_answer', models.BooleanField()),
                ('mini_quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_quiz.miniquiz')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_quiz.question')),
            ],
        ),
    ]
