# Generated by Django 5.1 on 2024-08-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='correct_answer_question_id',
            new_name='is_correct_answer',
        ),
    ]
