# Generated by Django 4.2.15 on 2024-09-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniquiz',
            name='time_limit',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='playerdoes',
            name='attempt_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='playerdoes',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
