# Generated by Django 4.2.15 on 2024-09-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_quiz', '0002_alter_miniquiz_time_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdoes',
            name='attempt_id',
            field=models.IntegerField(default=0),
        ),
    ]
