# Generated by Django 4.2.15 on 2024-09-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_quiz', '0003_playerdoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdoes',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
