# Generated by Django 4.2.15 on 2024-10-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_quiz', '0003_alter_playerdoes_attempt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniquiz',
            name='title',
            field=models.CharField(default='temporary', max_length=50),
            preserve_default=False,
        ),
    ]
